version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  build:
    commands:
      - echo Build started on 'date'
  post_build:
    commands:
      - aws s3 cp javaWeb.zip s3://test-bucket-seshu/build-backup

artifacts:
  files:
    - target/*
  discard-paths: yes
