version: 0.1

phases:
  post_build:
    commands:
      - echo Build completed on 'date'
      - zip -r javaWeb.zip **/*
      - aws s3 cp javaWeb.zip s3://test-bucket-seshu/build-backup

artifacts:
  files:
    - '**/*'
  discard-paths: yes
