version: 0.1

phases:
  post_build:
    commands:
      - echo Build completed on 'date'
      - zip -r javaWeb.zip **/*
      - aws s3 cp javaWeb.zip s3://github-s3/files

artifacts:
  files:
    - '**/*'
  discard-paths: yes
